import type {
  User,
  Medication,
  Regimen,
  Inventory,
  FollowUp,
  MedicationEvent,
  FamilyMember,
  FamilyFeedItem,
} from '@/types';
import { dayjs } from '@/utils/date';
import { generateScheduledEvents } from '@/utils/eventGenerator';

export interface DbShape {
  users: User[];
  currentUserId: string;
  medications: Medication[];
  regimens: Regimen[];
  inventories: Inventory[];
  events: MedicationEvent[];
  followUps: FollowUp[];
  familyMembers: FamilyMember[];
  familyFeed: FamilyFeedItem[];
}

export function buildSeed(): DbShape {
  const userId = 'u_demo';
  const user: User = {
    id: userId,
    name: '张大爷',
    age: 68,
    gender: 'male',
    conditions: ['hypertension', 'type2_diabetes'],
    allergies: ['青霉素'],
    createdAt: dayjs().subtract(120, 'day').toISOString(),
  };

  const medications: Medication[] = [
    {
      id: 'med_amlo',
      userId,
      name: '氨氯地平片',
      spec: '5mg/片',
      form: 'tablet',
      unit: '片',
      purpose: '降压',
      prescribedBy: '张医生 / 北京协和',
      startDate: dayjs().subtract(30, 'day').format('YYYY-MM-DD'),
      endDate: null,
      createdAt: dayjs().subtract(30, 'day').toISOString(),
    },
    {
      id: 'med_metf',
      userId,
      name: '二甲双胍缓释片',
      spec: '0.5g/片',
      form: 'tablet',
      unit: '片',
      purpose: '降糖',
      prescribedBy: '李医生 / 协和',
      startDate: dayjs().subtract(60, 'day').format('YYYY-MM-DD'),
      endDate: null,
      createdAt: dayjs().subtract(60, 'day').toISOString(),
    },
    {
      id: 'med_aspr',
      userId,
      name: '阿司匹林肠溶片',
      spec: '100mg/片',
      form: 'tablet',
      unit: '片',
      purpose: '抗血小板',
      prescribedBy: '张医生 / 北京协和',
      startDate: dayjs().subtract(15, 'day').format('YYYY-MM-DD'),
      endDate: null,
      createdAt: dayjs().subtract(15, 'day').toISOString(),
    },
  ];

  const regimens: Regimen[] = [
    {
      id: 'reg_amlo',
      medicationId: 'med_amlo',
      dosage: 1,
      unit: '片',
      frequency: { type: 'daily', timesPerDay: 1, times: ['08:00'] },
      withFood: 'after',
      notes: '清晨饭后温水送服',
    },
    {
      id: 'reg_metf',
      medicationId: 'med_metf',
      dosage: 1,
      unit: '片',
      frequency: { type: 'daily', timesPerDay: 2, times: ['08:00', '20:00'] },
      withFood: 'with',
      notes: '随餐服用',
    },
    {
      id: 'reg_aspr',
      medicationId: 'med_aspr',
      dosage: 1,
      unit: '片',
      frequency: { type: 'daily', timesPerDay: 1, times: ['21:00'] },
      withFood: 'after',
      notes: '睡前服用',
    },
  ];

  const inventories: Inventory[] = [
    {
      id: 'inv_amlo',
      medicationId: 'med_amlo',
      quantity: 18,
      unit: '片',
      lowStockThresholdDays: 5,
      lastRestockedAt: dayjs().subtract(10, 'day').format('YYYY-MM-DD'),
      lastRestockAmount: 30,
    },
    {
      id: 'inv_metf',
      medicationId: 'med_metf',
      quantity: 6, // intentionally low → trigger warning
      unit: '片',
      lowStockThresholdDays: 5,
      lastRestockedAt: dayjs().subtract(20, 'day').format('YYYY-MM-DD'),
      lastRestockAmount: 60,
    },
    {
      id: 'inv_aspr',
      medicationId: 'med_aspr',
      quantity: 25,
      unit: '片',
      lowStockThresholdDays: 5,
      lastRestockedAt: dayjs().subtract(5, 'day').format('YYYY-MM-DD'),
      lastRestockAmount: 30,
    },
  ];

  // Generate past 14 days + future 14 days events for demo realism
  const from = dayjs().subtract(14, 'day').toDate();
  const to = dayjs().add(14, 'day').toDate();
  const events = generateScheduledEvents({
    userId,
    medications,
    regimens,
    from,
    to,
  });

  // Mark some past events as taken / missed to seed adherence stats
  const now = dayjs();
  for (const e of events) {
    const sched = dayjs(e.scheduledAt);
    if (sched.isAfter(now)) continue;
    // Simulate ~85% adherence with a couple of recent misses on metformin
    const r = Math.random();
    if (e.medicationId === 'med_metf' && sched.isAfter(now.subtract(2, 'day'))) {
      // recent 2 days missing some metformin doses
      e.status = r < 0.5 ? 'missed' : 'taken';
    } else {
      e.status = r < 0.85 ? 'taken' : 'missed';
    }
    if (e.status === 'taken') {
      e.takenAt = sched.add(Math.floor(Math.random() * 30), 'minute').toISOString();
    }
  }

  const followUps: FollowUp[] = [
    {
      id: 'fu_1',
      userId,
      relatedMedicationIds: ['med_amlo', 'med_aspr'],
      hospital: '北京协和医院',
      department: '心内科',
      doctor: '张医生',
      scheduledDate: dayjs().add(12, 'day').format('YYYY-MM-DD'),
      reason: '复查血压 + 续方',
      status: 'upcoming',
      autoGenerated: true,
    },
  ];

  const familyMembers: FamilyMember[] = [
    {
      id: 'fm_self',
      name: '张大爷',
      role: 'patient',
      relation: '本人',
      notify: false,
      avatarColor: '#FFC300',
      joinedAt: dayjs().subtract(60, 'day').toISOString(),
    },
    {
      id: 'fm_son',
      name: '小张',
      role: 'guardian',
      relation: '儿子',
      phone: '138****0001',
      notify: true,
      avatarColor: '#FF8C00',
      joinedAt: dayjs().subtract(58, 'day').toISOString(),
    },
    {
      id: 'fm_daughter',
      name: '张小妹',
      role: 'guardian',
      relation: '女儿',
      phone: '139****0002',
      notify: true,
      avatarColor: '#22A06B',
      joinedAt: dayjs().subtract(50, 'day').toISOString(),
    },
  ];

  const familyFeed: FamilyFeedItem[] = [
    {
      id: 'ff_0',
      type: 'system',
      title: '昨天',
      createdAt: dayjs().subtract(28, 'hour').toISOString(),
    },
    {
      id: 'ff_1',
      type: 'cheer',
      title: '爸，今天降温了，记得添件衣服。',
      byMemberId: 'fm_daughter',
      createdAt: dayjs().subtract(26, 'hour').toISOString(),
    },
    {
      id: 'ff_2',
      type: 'cheer',
      title: '收到，今天感觉还行，血压 132/82。',
      byMemberId: 'fm_self',
      createdAt: dayjs().subtract(25, 'hour').toISOString(),
    },
    {
      id: 'ff_3',
      type: 'cheer',
      title: '👍 还可以。早晚记得吃氨氯地平。',
      byMemberId: 'fm_son',
      createdAt: dayjs().subtract(24, 'hour').toISOString(),
    },
    {
      id: 'ff_4',
      type: 'dose_taken',
      title: '已服 氨氯地平片 1 片',
      byMemberId: 'fm_self',
      createdAt: dayjs().subtract(23, 'hour').toISOString(),
    },
    {
      id: 'ff_5',
      type: 'system',
      title: '今天',
      createdAt: dayjs().subtract(8, 'hour').toISOString(),
    },
    {
      id: 'ff_6',
      type: 'low_stock',
      title: '二甲双胍库存仅剩 3 天，记得补药',
      relatedMedId: 'med_metf',
      createdAt: dayjs().subtract(7, 'hour').toISOString(),
    },
    {
      id: 'ff_7',
      type: 'cheer',
      title: '我下班路过药店帮你买，别担心！',
      byMemberId: 'fm_son',
      createdAt: dayjs().subtract(6, 'hour').toISOString(),
    },
    {
      id: 'ff_8',
      type: 'cheer',
      title: '好嘞，谢谢儿子 ❤️',
      byMemberId: 'fm_self',
      createdAt: dayjs().subtract(5, 'hour').toISOString(),
    },
    {
      id: 'ff_9',
      type: 'dose_taken',
      title: '已服 二甲双胍缓释片 1 片',
      byMemberId: 'fm_self',
      createdAt: dayjs().subtract(2, 'hour').toISOString(),
    },
    {
      id: 'ff_10',
      type: 'cheer',
      title: '爸，周末一起去公园散散步呀？',
      byMemberId: 'fm_daughter',
      createdAt: dayjs().subtract(40, 'minute').toISOString(),
    },
  ];

  return {
    users: [user],
    currentUserId: userId,
    medications,
    regimens,
    inventories,
    events,
    followUps,
    familyMembers,
    familyFeed,
  };
}
