export type ConditionCode =
  | 'hypertension'
  | 'type2_diabetes'
  | 'hyperlipidemia'
  | 'coronary_heart_disease'
  | 'chronic_kidney_disease'
  | 'other';

export interface User {
  id: string;
  name: string;
  age: number;
  gender: 'male' | 'female' | 'other';
  conditions: ConditionCode[];
  allergies: string[];
  createdAt: string;
}

export type MedicationForm = 'tablet' | 'capsule' | 'liquid' | 'injection' | 'other';

export interface Medication {
  id: string;
  userId: string;
  name: string;
  spec: string; // e.g. 5mg/片
  form: MedicationForm;
  unit: string; // 片/粒/ml
  purpose: string; // 降压
  prescribedBy?: string;
  startDate: string; // YYYY-MM-DD
  endDate?: string | null;
  createdAt: string;
}

export type FrequencyType = 'daily' | 'weekly' | 'interval';

export interface Frequency {
  type: FrequencyType;
  timesPerDay: number; // for daily/weekly
  times: string[]; // HH:mm
  weekdays?: number[]; // 1-7 (Mon-Sun) for weekly
  intervalDays?: number; // for interval (e.g. every 2 days)
}

export type WithFood = 'before' | 'with' | 'after' | 'any';

export interface Regimen {
  id: string;
  medicationId: string;
  dosage: number;
  unit: string;
  frequency: Frequency;
  withFood: WithFood;
  notes?: string;
}

export interface Inventory {
  id: string;
  medicationId: string;
  quantity: number;
  unit: string;
  lowStockThresholdDays: number;
  lastRestockedAt?: string;
  lastRestockAmount?: number;
}

export type EventStatus = 'pending' | 'taken' | 'missed' | 'skipped';

export interface MedicationEvent {
  id: string;
  userId: string;
  medicationId: string;
  regimenId: string;
  scheduledAt: string; // ISO
  status: EventStatus;
  takenAt?: string | null;
  dosage: number;
  unit: string;
  source: 'auto' | 'manual';
}

export type FollowUpStatus = 'upcoming' | 'done' | 'cancelled';

export interface FollowUp {
  id: string;
  userId: string;
  relatedMedicationIds: string[];
  hospital?: string;
  department?: string;
  doctor?: string;
  scheduledDate: string; // YYYY-MM-DD
  reason?: string;
  status: FollowUpStatus;
  autoGenerated: boolean;
}

export type FamilyRole = 'patient' | 'guardian' | 'doctor' | 'other';

export interface FamilyMember {
  id: string;
  name: string;
  role: FamilyRole;
  phone?: string;
  relation?: string; // 儿子 / 女儿 / 配偶
  notify: boolean; // 是否接收推送提醒
  avatarColor?: string;
  joinedAt: string;
}

export type FamilyEventType =
  | 'dose_taken'
  | 'dose_missed'
  | 'low_stock'
  | 'restock'
  | 'follow_up'
  | 'cheer'      // 家人留言（普通气泡）
  | 'system';    // 系统提示（居中灰条）

export interface FamilyFeedItem {
  id: string;
  type: FamilyEventType;
  title: string;
  body?: string;
  byMemberId?: string; // 谁发起的（系统事件可空）
  relatedMedId?: string;
  createdAt: string;
}

export type InsightType = 'adherence' | 'stock' | 'risk' | 'tip';
export type InsightLevel = 'info' | 'warn' | 'danger';

export interface Insight {
  id: string;
  userId: string;
  type: InsightType;
  level: InsightLevel;
  title: string;
  body: string;
  relatedIds?: string[];
  createdAt: string;
}
