import { useMemo, useState } from 'react';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Modal } from '@/components/ui/Modal';
import { Field, TextInput, Select } from '@/components/ui/Input';
import { Tag } from '@/components/ui/Tag';
import { useAppStore } from '@/store';
import { dayjs } from '@/utils/date';
import { buildFollowUpIcs, downloadFile } from '@/utils/share';

export function FollowUp() {
  const followUps = useAppStore((s) => s.followUps);
  const meds = useAppStore((s) => s.medications);
  const addFollowUp = useAppStore((s) => s.addFollowUp);
  const updateFollowUp = useAppStore((s) => s.updateFollowUp);
  const removeFollowUp = useAppStore((s) => s.removeFollowUp);

  const [open, setOpen] = useState(false);
  const [scheduledDate, setScheduledDate] = useState(dayjs().add(14, 'day').format('YYYY-MM-DD'));
  const [hospital, setHospital] = useState('');
  const [department, setDepartment] = useState('');
  const [doctor, setDoctor] = useState('');
  const [reason, setReason] = useState('');
  const [relatedMedicationId, setRelatedMedicationId] = useState<string>('');

  const upcoming = useMemo(
    () => followUps.filter((f) => f.status === 'upcoming').sort((a, b) => a.scheduledDate.localeCompare(b.scheduledDate)),
    [followUps]
  );
  const past = useMemo(
    () => followUps.filter((f) => f.status !== 'upcoming').sort((a, b) => b.scheduledDate.localeCompare(a.scheduledDate)),
    [followUps]
  );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl md:text-2xl font-bold">复诊安排</h2>
          <p className="text-ink-500 mt-1">即将复诊 {upcoming.length} 项</p>
        </div>
        <Button size="lg" onClick={() => setOpen(true)}>
          + 新建复诊
        </Button>
      </div>

      {upcoming.length === 0 ? (
        <Card>
          <p className="text-ink-500">暂无即将复诊的安排。</p>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {upcoming.map((f) => {
            const days = dayjs(f.scheduledDate).diff(dayjs(), 'day');
            return (
              <Card key={f.id}>
                <div className="flex items-start justify-between gap-3">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 flex-wrap">
                      <h3 className="font-semibold text-lg">{f.scheduledDate}</h3>
                      {days <= 7 && days >= 0 && <Tag variant="warn">{days <= 0 ? '今天' : `${days} 天后`}</Tag>}
                      {f.autoGenerated && <Tag variant="info">自动生成</Tag>}
                    </div>
                    <p className="text-ink-700 mt-2">
                      {f.hospital} {f.department} {f.doctor && ` · ${f.doctor}`}
                    </p>
                    {f.reason && <p className="text-ink-500 text-sm mt-1">{f.reason}</p>}
                    {f.relatedMedicationIds.length > 0 && (
                      <div className="flex flex-wrap gap-1 mt-2">
                        {f.relatedMedicationIds.map((id) => {
                          const m = meds.find((x) => x.id === id);
                          return m ? <Tag key={id}>{m.name}</Tag> : null;
                        })}
                      </div>
                    )}
                  </div>
                </div>
                <div className="flex gap-2 mt-4 flex-wrap">
                  <Button
                    variant="secondary"
                    size="lg"
                    onClick={() => updateFollowUp(f.id, { status: 'done' })}
                  >
                    标记已完成
                  </Button>
                  <Button
                    variant="secondary"
                    size="lg"
                    onClick={() =>
                      downloadFile(
                        `followup-${f.scheduledDate}.ics`,
                        buildFollowUpIcs(f)
                      )
                    }
                  >
                    📅 加入日历
                  </Button>
                  <Button
                    variant="ghost"
                    size="lg"
                    onClick={() => removeFollowUp(f.id)}
                  >
                    删除
                  </Button>
                </div>
              </Card>
            );
          })}
        </div>
      )}

      {past.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold text-ink-700 mb-3">历史</h3>
          <div className="space-y-2">
            {past.map((f) => (
              <div key={f.id} className="card flex items-center justify-between">
                <div>
                  <div className="font-medium">{f.scheduledDate}</div>
                  <div className="text-sm text-ink-500">{f.hospital} {f.department}</div>
                </div>
                <Tag variant={f.status === 'done' ? 'success' : 'warn'}>
                  {f.status === 'done' ? '已完成' : '已取消'}
                </Tag>
              </div>
            ))}
          </div>
        </div>
      )}

      <Modal
        open={open}
        onClose={() => setOpen(false)}
        title="新建复诊"
        footer={
          <>
            <Button variant="ghost" onClick={() => setOpen(false)}>取消</Button>
            <Button
              onClick={async () => {
                await addFollowUp({
                  scheduledDate,
                  hospital: hospital.trim() || undefined,
                  department: department.trim() || undefined,
                  doctor: doctor.trim() || undefined,
                  reason: reason.trim() || undefined,
                  relatedMedicationIds: relatedMedicationId ? [relatedMedicationId] : [],
                  status: 'upcoming',
                  autoGenerated: false,
                });
                setOpen(false);
                setReason('');
              }}
            >
              确认创建
            </Button>
          </>
        }
      >
        <Field label="复诊日期">
          <TextInput type="date" value={scheduledDate} onChange={(e) => setScheduledDate(e.target.value)} />
        </Field>
        <Field label="医院">
          <TextInput value={hospital} onChange={(e) => setHospital(e.target.value)} placeholder="北京协和" />
        </Field>
        <Field label="科室">
          <TextInput value={department} onChange={(e) => setDepartment(e.target.value)} placeholder="心内科" />
        </Field>
        <Field label="医生（可选）">
          <TextInput value={doctor} onChange={(e) => setDoctor(e.target.value)} placeholder="张医生" />
        </Field>
        <Field label="事由（可选）">
          <TextInput value={reason} onChange={(e) => setReason(e.target.value)} placeholder="复查血压 + 续方" />
        </Field>
        <Field label="关联药品（可选）">
          <Select value={relatedMedicationId} onChange={(e) => setRelatedMedicationId(e.target.value)}>
            <option value="">不关联</option>
            {meds.map((m) => (
              <option key={m.id} value={m.id}>{m.name}</option>
            ))}
          </Select>
        </Field>
      </Modal>
    </div>
  );
}
